### ISSUE TITLE
generic用nacos注册中心，client调用不了

### ISSUE THREAD

**Issue by wereset** [apache/dubbo-go-samples#321]
操作系统：
Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020

golang版本：
go version go1.16.7 linux/amd64

demo的git提交ID：
SHA-1: f0d1e1076397a4736de080ffb16cd0963c8c2f9d

修改server配置如下：
`dubbo:
  registries:
    nacos:
      protocol: nacos
      timeout: 3s
      address: 192.168.1.202:8848
      username: nacos
      password: 11111111111111111 
      group: YEAHGO_TEST # nacos group, default is DEFAULT_GROUP
  protocols:
    dubbo:
      name: dubbo
      port: 20000
    triple:
      name: tri
      port: 20001
  provider:
    registry-ids: nacos
    services:
      UserProvider:
        serialization: hessian2
        interface: org.apache.dubbo.samples.UserProvider
      UserProviderTriple:
        serialization: hessian2
        interface: org.apache.dubbo.samples.UserProviderTriple`

修改client配置如下：
`func newRefConf(iface, protocol string) config.ReferenceConfig {
	registryConfig := &config.RegistryConfig{
		Protocol: "nacos",
		Address:  "192.168.1.202:8848",
		Username: "nacos",
		Password: "11111111111111111 ",
		Group: "YEAHGO_TEST",
	}

	refConf := config.ReferenceConfig{
		InterfaceName: iface,
		Cluster:       "failover",
		RegistryIDs:   []string{"nacosTest"},
		Protocol:      protocol,
		Generic:       "true",
	}

	rootConfig := config.NewRootConfigBuilder().
		AddRegistry("nacosTest", registryConfig).
		Build()
	if err := config.Load(config.WithRootConfig(rootConfig)); err != nil {
		panic(err)
	}
	_ = refConf.Init(rootConfig)
	refConf.GenericLoad(appName)

	return refConf
}`

运行日志如下：
`[root@localhost go-client]# go run ./cmd/client.go 
2022-04-28T14:35:26.628+0800	INFO	config/root_config.go:153	[Config Center] Config center doesn't start
2022-04-28T14:35:26.629+0800	INFO	nacos/registry.go:270	[Nacos Registry] New nacos registry with url = map[host:192.168.1.202 password:11111111111111111 port:8848 protocol:nacos registry:nacos registry.group:YEAHGO_TEST registry.label:true registry.namespace: registry.preferred:false registry.role:0 registry.timeout:5s registry.ttl:10s registry.weight:0 registry.zone: remote-client-name:dubbo.registries-nacos-192.168.1.202:8848 simplified:false username:nacos]
2022-04-28T14:35:26.629+0800	INFO	nacos/builder.go:138	[Nacos Client] New nacos client with config = [{Scheme: ContextPath: IpAddr:192.168.1.202 Port:8848}]
2022-04-28T14:35:26.629+0800	INFO	nacos_client/nacos_client.go:79	logDir:</www/wwwroot/project/dubbo/demo/dubbo-go-samples/generic/default/go-client/log>   cacheDir:</www/wwwroot/project/dubbo/demo/dubbo-go-samples/generic/default/go-client/cache>
2022-04-28T14:35:26.742+0800	INFO	naming_client/push_receiver.go:80	udp server start, port: 55476
2022-04-28T14:35:26.743+0800	INFO	v3router/router_chain.go:55	[NewUniformRouterChain] Config center does not start, please check if the configuration center has been properly configured in dubbogo.yml
2022-04-28T14:35:26.743+0800	INFO	nacos/registry.go:125	[Nacos Registry] Registry instance with param = {Ip:192.168.137.10 Port:80 Weight:1 Enable:true Healthy:true Metadata:map[app.version:3.0.0 application:dubbo.io async:false bean.name:dubbo.io cluster:failover config.tracing: environment:dev generic:true group: interface:org.apache.dubbo.samples.UserProvider loadbalance: metadata-type:local methods: module:sample nacos.category:consumers name:dubbo.io organization:dubbo-go owner:dubbo-go path:/org.apache.dubbo.samples.UserProvider protocol:dubbo provided-by: reference.filter:generic,cshutdown registry.role:0 release:dubbo-golang-3.0.0 retries: serialization: side:consumer sticky:false timestamp:1651127726 version:] ClusterName: ServiceName:consumers:org.apache.dubbo.samples.UserProvider:: GroupName:YEAHGO_TEST Ephemeral:true}
2022-04-28T14:35:26.743+0800	INFO	naming_client/naming_proxy.go:54	register instance namespaceId:<>,serviceName:<YEAHGO_TEST@@consumers:org.apache.dubbo.samples.UserProvider::> with instance:<{"valid":false,"marked":false,"instanceId":"","port":80,"ip":"192.168.137.10","weight":1,"metadata":{"app.version":"3.0.0","application":"dubbo.io","async":"false","bean.name":"dubbo.io","cluster":"failover","config.tracing":"","environment":"dev","generic":"true","group":"","interface":"org.apache.dubbo.samples.UserProvider","loadbalance":"","metadata-type":"local","methods":"","module":"sample","nacos.category":"consumers","name":"dubbo.io","organization":"dubbo-go","owner":"dubbo-go","path":"/org.apache.dubbo.samples.UserProvider","protocol":"dubbo","provided-by":"","reference.filter":"generic,cshutdown","registry.role":"0","release":"dubbo-golang-3.0.0","retries":"","serialization":"","side":"consumer","sticky":"false","timestamp":"1651127726","version":""},"clusterName":"","serviceName":"","enabled":true,"healthy":true,"ephemeral":true}>
2022-04-28T14:35:26.743+0800	INFO	naming_client/subscribe_callback.go:39	adding YEAHGO_TEST@@providers:org.apache.dubbo.samples.UserProvider:: with  to listener map
2022-04-28T14:35:26.743+0800	INFO	util/common.go:94	Local IP:192.168.137.10
2022-04-28T14:35:26.772+0800	INFO	naming_client/beat_reactor.go:68	adding beat: <{"ip":"192.168.137.10","port":80,"weight":1,"serviceName":"YEAHGO_TEST@@consumers:org.apache.dubbo.samples.UserProvider::","cluster":"","metadata":{"app.version":"3.0.0","application":"dubbo.io","async":"false","bean.name":"dubbo.io","cluster":"failover","config.tracing":"","environment":"dev","generic":"true","group":"","interface":"org.apache.dubbo.samples.UserProvider","loadbalance":"","metadata-type":"local","methods":"","module":"sample","nacos.category":"consumers","name":"dubbo.io","organization":"dubbo-go","owner":"dubbo-go","path":"/org.apache.dubbo.samples.UserProvider","protocol":"dubbo","provided-by":"","reference.filter":"generic,cshutdown","registry.role":"0","release":"dubbo-golang-3.0.0","retries":"","serialization":"","side":"consumer","sticky":"false","timestamp":"1651127726","version":""},"scheduled":false}> to beat map
2022-04-28T14:35:26.772+0800	WARN	proxy/proxy.go:210	[CallProxy] received rpc err: Failed to invoke the method $invoke. No provider available for the service dubbo://:@192.168.137.10:80/?interface=org.apache.dubbo.samples.UserProvider&group=&version= from registry nacos://nacos:11111111111111111@192.168.1.202:8848?nacos.access=&nacos.group=YEAHGO_TEST&nacos.namespaceId=&nacos.password=11111111111111111&nacos.secret=&nacos.timeout=5s&nacos.username=nacos&registry=nacos&registry.group=YEAHGO_TEST&registry.label=true&registry.namespace=&registry.preferred=false&registry.role=0&registry.timeout=5s&registry.ttl=10s&registry.weight=0&registry.zone=&remote-client-name=dubbo.registries-nacos-192.168.1.202%3A8848&simplified=false on the consumer 192.168.137.10 using the dubbo version 3.0.0 .Please check if the providers have been started and registered.
panic: Failed to invoke the method $invoke. No provider available for the service dubbo://:@192.168.137.10:80/?interface=org.apache.dubbo.samples.UserProvider&group=&version= from registry nacos://nacos:11111111111111111@192.168.1.202:8848?nacos.access=&nacos.group=YEAHGO_TEST&nacos.namespaceId=&nacos.password=11111111111111111&nacos.secret=&nacos.timeout=5s&nacos.username=nacos&registry=nacos&registry.group=YEAHGO_TEST&registry.label=true&registry.namespace=&registry.preferred=false&registry.role=0&registry.timeout=5s&registry.ttl=10s&registry.weight=0&registry.zone=&remote-client-name=dubbo.registries-nacos-192.168.1.202%3A8848&simplified=false on the consumer 192.168.137.10 using the dubbo version 3.0.0 .Please check if the providers have been started and registered.

goroutine 1 [running]:
main.callGetUser(0xc0002ae1e0, 0x177715b, 0x8, 0x17a14cc, 0x25, 0xc0001e8558, 0x0, 0x0, 0x0, 0x0, ...)
	/www/wwwroot/project/dubbo/demo/dubbo-go-samples/generic/default/go-client/cmd/client.go:79 +0x8b3
main.main()
	/www/wwwroot/project/dubbo/demo/dubbo-go-samples/generic/default/go-client/cmd/client.go:50 +0xd8`

**Comment by Lvnszn** [comment]
最近测试 MergeURL 的时候我也碰到这个问题，可以先多尝试启动几下试试。

**Comment by Lvnszn** [comment]
方便的话也提供一下注册中心的日志

**Comment by Lvnszn** [comment]
暂时缓解的方法是 newRefConf 函数调用genericLoad 之后 sleep  3s 一下不会有这个问题， @binbin0325 大佬正在帮忙看这块逻辑

**Comment by DavidYan2000** [comment]
还没解决吗。。看到几个issue都是这个问题
