### ISSUE TITLE
dubbo-go generic  client  3.0.4 

### ISSUE THREAD

**Issue by xyjboys** [apache/dubbo-go-samples#604]
2023-09-04 16:05:40     INFO    zookeeper/client.go:53  [Zookeeper Client] New zookeeper client with name = 127.0.0.1:2181, zkAddress = 127.0.0.1:2181, timeout = 5s
2023/09/04 16:05:40 Connected to 127.0.0.1:2181
2023/09/04 16:05:40 Connected to 127.0.0.1:2181
2023/09/04 16:05:40 Authenticated: id=72057935878946844, timeout=5000
2023/09/04 16:05:40 Re-submitting `0` credentials after reconnect
2023/09/04 16:05:40 Authenticated: id=72057935878946843, timeout=5000
2023/09/04 16:05:40 Re-submitting `0` credentials after reconnect
2023-09-04 16:05:40     ERROR   zookeeper/service_discovery.go:177      [zkServiceDiscovery] Could not query the instances for service{dubbo.io}, error = err{Error while invoking zk.Children(path:/services/dubbo.io), the reason maybe is: : zk: node does not exist}
2023-09-04 16:05:40     WARN    tag/router.go:52        [tag router] invokers from previous router is empty
2023-09-04 16:05:40     WARN    proxy/proxy.go:212      [CallProxy] received rpc err: Failed to invoke the method $invoke. No provider available for the service dubbo://:@:/?interface=org.apache.dubbo.samples.UserProvider&group=&version= from registry service-discovery-registry://127.0.0.1:2181?registry=zookeeper&registry.group=&registry.label=true&registry.namespace=&registry.preferred=false&registry.role=0&registry.timeout=5s&registry.ttl=15m&registry.weight=0&registry.zone=&remote-client-name=dubbo.registries-zookeeper-127.0.0.1%3A2181&simplified=false on the consumer 172.17.51.111 using the dubbo version 3.0.4 .Please check if the providers have been started and registered.
panic: Failed to invoke the method $invoke. No provider available for the service dubbo://:@:/?interface=org.apache.dubbo.samples.UserProvider&group=&version= from registry service-discovery-registry://127.0.0.1:2181?registry=zookeeper&registry.group=&registry.label=true&registry.namespace=&registry.preferred=false&registry.role=0&registry.timeout=5s&registry.ttl=15m&registry.weight=0&registry.zone=&remote-client-name=dubbo.registries-zookeeper-127.0.0.1%3A2181&simplified=false on the consumer 172.17.51.111 using the dubbo version 3.0.4 .Please check if the providers have been started and registered.

goroutine 1 [running]:
dubbo-go-client/client_dubbo.callGetUser({0xc0003ee280, {0x1a4385f, 0x8}, {0x1a7c2af, 0x25}, 0xc0007050d8, {0x0, 0x0}, {0x0, 0x0}, ...})
        C:/Users/xiaoyj/go/dubbo-go-client/client_dubbo/client.go:73 +0x625
dubbo-go-client/client_dubbo.Call()
        C:/Users/xiaoyj/go/dubbo-go-client/client_dubbo/client.go:44 +0xc5
main.main()
        C:/Users/xiaoyj/go/dubbo-go-client/main.go:9 +0x17
exit status 2

这里启用了示例中的 java 的服务端  尝试用java 示例中客户端可以正常调用，但是用go 客户端就出现这个问题

**Comment by xyjboys** [comment]
![1693822344702](https://github.com/apache/dubbo-go-samples/assets/24861354/65c1caa2-377a-431f-acc3-8892af83c697)
需要指定这个参数
